import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#f1dfd0',
        'on-tertiary-fixed': '#1e1b17',
        'secondary-container': '#ff52b0',
        'on-error-container': '#93000a',
        'surface-container-low': '#fff1e7',
        'on-primary': '#ffffff',
        'on-surface': '#231a11',
        primary: '#802a00',
        'primary-fixed-dim': '#ffb59a',
        'on-surface-variant': '#58423a',
        'on-secondary-container': '#5f003b',
        'surface-container-high': '#f7e5d6',
        'on-secondary': '#ffffff',
        'on-background': '#231a11',
        'on-primary-container': '#ffcebc',
        background: '#fff8f4',
        surface: '#fff8f4',
        'surface-dim': '#e9d7c8',
        'primary-container': '#a83900',
        'inverse-primary': '#ffb59a',
        'error-container': '#ffdad6',
        'surface-tint': '#a83900',
        'accent-pink': '#ff3cac',
        outline: '#8c7168',
        'on-secondary-fixed': '#3d0024',
        'tertiary-fixed-dim': '#ccc5bf',
        'surface-variant': '#f1dfd0',
        'on-primary-fixed': '#380d00',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#8b0059',
        'surface-container': '#fdebdc',
        'primary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffafd1',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fff8f4',
        'tertiary-fixed': '#e8e1db',
        secondary: '#b50675',
        'inverse-surface': '#392e25',
        'tertiary-container': '#625e59',
        'on-tertiary-fixed-variant': '#4a4642',
        tertiary: '#4a4642',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#802a00',
        'surface-container-lowest': '#ffffff',
        'primary-orange': '#ff6b2b',
        'secondary-fixed': '#ffd8e6',
        'on-tertiary-container': '#ded8d1',
        'inverse-on-surface': '#ffeee0',
        'outline-warm': '#8d7167',
        'outline-variant': '#e0c0b5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'be-vietnam': ['Be Vietnam Pro', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
